Header header
int64 tape_detect  # 0: tape not detected; 1: tape detected
int64 left_marker  # 0: left marker not detected; 1: left marker detected
int64 right_marker  # 0: right marker not detected; 1: right marker detected
float32 u   # target detection coordinate u in image 
float32 v   # target detection coordinate v in image  
float32 x   # target detection position x in sensor frame
float32 y   # target detection position y in sensor frame
float32 z   # target detection position y in sensor frame
